HomeWork
AlexsandrKovalsky/Qt pull request #1
Opened 2020-03-28 07:59 UTC by AlexsandrKovalsky

2020-04-01 12:37 UTC, mashinapetro requested changes

2020-04-01 12:37 UTC, mashinapetro commented on HomeWork2/Net/manager.h
> +signals:
А где сигналы? Мы договорились, что у нас будет два сигнала - для информирования о том, что выполнилась авторизаци и регистрация. 
Сигнал после авторизацию должен передавать две строки - с ошибкой и с токеном. Если ошибки нет, первая строка должна быть пустая.
Сигнал после авторизации должен передавать одну строку - с ошибкой. Если ошибки нет, строка должна быть пустая.

2020-04-01 12:37 UTC, mashinapetro commented on HomeWork2/authorization/LoginForm.qml
> +
Лишние строки. Надо удалить.

2020-04-01 12:37 UTC, mashinapetro commented on HomeWork2/authorization/RegistrationForm.qml
> +        enabled: loginUp.text.length<6||
Условие неправильное.

2020-04-04 06:20 UTC, IAlmostDeveloper commented on HomeWork2/Net/manager.h
> +    void onAuthFinished(QString &error, QString &token);
slots - это функции, которые можно вызывать внутри компонента QML. Функции-сигналы, которые используются с emit, должны находиться в signals.

2020-04-04 06:35 UTC, IAlmostDeveloper commented on HomeWork2/authorization/LoginForm.qml
> +    id: loginForm
id loginForm нигде не используется.

2020-04-04 06:35 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +    id: registrationForm
id registrationForm нигде не используется.

2020-04-04 06:35 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +    }
Вместо якорей можно использовать компонент Column.

2020-04-04 06:35 UTC, IAlmostDeveloper commented on HomeWork2/authorization/main.qml
> +                : "qrc:/qml/RegistrationForm.qml"
При добавлении новых форм условие будет расширяться. Можно использовать свойство-словарь, тогда условие всегда будет занимать одну строку кода вне зависимости от количества форм.

2020-04-04 06:35 UTC, IAlmostDeveloper commented on HomeWork2/authorization/main.qml
> +    }
Можно использовать Row.

2020-04-04 12:36 UTC, IAlmostDeveloper reviewed
Норм, но есть пара моментов где стоит исправить.

2020-04-04 12:36 UTC, IAlmostDeveloper commented on HomeWork2/authorization/LoginForm.qml
> +                     passwordIn.text.length<6 ? false:true
Можно упростить до login.text.length >=5 && password.text.length>=5

2020-04-04 12:36 UTC, IAlmostDeveloper commented on HomeWork2/authorization/LoginForm.qml
> +            running: false
Можно создать property, которое будет говорить нам, проходит ли сейчас процесс авторизации, и забиндить на него свойство индикатора running.

2020-04-04 12:36 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +        }
По желанию, можешь покурить диалоговые окна в QML, и выводить ошибки через них.

2020-04-04 12:36 UTC, IAlmostDeveloper commented on HomeWork2/Net/manager.h
>      void onAuthFinished(QString &error, QString &token);
Теперь норм. На будущее, сигналы можно называть без приставки on, при использовании их в компоненте QML приставка on будет добавляться сама.

2020-04-04 12:36 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +                     passwordIn.text.length<6 ? false:true
Можно упростить до loginIn.text.length >= 5 && passwordIn.text.length >= 5.

2020-04-05 13:26 UTC, IAlmostDeveloper commented on HomeWork2/authorization/LoginForm.qml
> +                     passwordIn.text.length<6 ? false:true
Ок.

2020-04-05 13:28 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +                     passwordIn.text.length<6 ? false:true
Ок.

2020-04-05 13:31 UTC, IAlmostDeveloper commented on HomeWork2/Net/manager.h
> +signals:
Ок.

2020-04-05 13:32 UTC, IAlmostDeveloper commented on HomeWork2/authorization/LoginForm.qml
> +
Ок.

2020-04-05 13:32 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +        enabled: loginUp.text.length<6||
Ок.

2020-04-05 13:32 UTC, IAlmostDeveloper commented on HomeWork2/Net/manager.h
> +    void onAuthFinished(QString &error, QString &token);
Ок.

2020-04-05 13:33 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +    }
Ок.

2020-04-05 13:33 UTC, IAlmostDeveloper commented on HomeWork2/authorization/LoginForm.qml
> +    id: loginForm
Ок.

2020-04-05 13:33 UTC, IAlmostDeveloper commented on HomeWork2/authorization/RegistrationForm.qml
> +    id: registrationForm
Ок.

2020-04-05 13:34 UTC, IAlmostDeveloper commented on HomeWork2/authorization/main.qml
> +    }
Ок.

2020-04-05 13:34 UTC, IAlmostDeveloper commented on HomeWork2/authorization/main.qml
> +                : "qrc:/qml/RegistrationForm.qml"
Ок.

2020-04-06 06:37 UTC, mashinapetro approved these changes

2020-04-06 06:40 UTC, merged